# Site settings
title:           GPES
title_separator: "|"
name:            "Grupo de Pesquisa em Engenharia de Software"
description: >- # this means to ignore newlines until "baseurl:"
                 Grupo de Pesquisa em Engenharia de Software.
baseurl:         "" # the subpath of your site, e.g. /blog
url:             "https://gpes.github.io" # the base hostname & protocol for your site, e.g. http://example.com
email:           your-email@example.com
locale:          "pt-BR"
timezone:        America/Fortaleza

# Build settings
markdown:        kramdown
permalink:       /:categories/:title/
remote_theme:    "mmistakes/minimal-mistakes@4.19.1"
plugins:
  - jekyll-feed
  - jekyll-include-cache

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
paginate: 5
collections:
  researchers:
    output: true
    permalink: /researcher/:path/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _researchers
  - scope:
      path: ""
      type: researcher
    values:
      layout: single
      author_profile: true
      share: false

# Minimal Mistakes configuration
minimal_mistakes_skin: "mint"
logo: "assets/images/logo.png"

breadcrumbs: true
breadcrumb_home_label : "Início"
breadcrumb_separator  : "/"

read_time: true
search: true

comments:
  provider: "disqus"
  disqus:
    shortname: "gpes"

include: ["_pages"]