title: GPES - Grupo de Pesquisa em Engenharia de Software
version: 0.1-beta
timezone: America/Fortaleza
email: your-email@domain.com
description: Descrição do site
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gpes.github.io" # the base hostname & protocol for your site
gcse: 003660541522496356862:fok5uapzili

future: false
lsi: false

# Pagination settings
# To change the number of posts to show on blog listing, just change
# 'paginate' property
paginate: 5
paginate_path: "/blog/page/:num"

# Authors
authors:
  gpes:
    name: Grupo de Pequisa em Engenharia de Software
    display_name: GPES
  diogomoreira:
    name: Diogo Dantas Moreira
    display_name: Diogo Moreira
    avatar: e84f43676db1e71be52dd9a12f6327ae
    email: 
    web: 
    twitter_username:
    github_username:
    minibio: Professor e Engenheiro de Software.

# Build settings
markdown: kramdown
exclude: [
  "_src",
  "bower_components/",
  "node_modules/",
  "package.json",
  "Gruntfile.js",
  "bower.json",
  "LICENSE",
  "README.md"
]
gems:
  - jekyll-mentions
  - jekyll-paginate